version: '2'
services:
  dnsdock:
    image: aacebedo/dnsdock:latest-amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: dnsdock-manual
    ports:
      - 53:53/udp